# values.yaml
image:
  repository: infralightio/flytube
  tag: latest
  pullPolicy: Always

env:
  user: ""
  remoteHost: ""
  sourcePort: ""
  targetHost: ""
  targetPort: ""

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
