# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flytube.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "flytube.name" . }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "flytube.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "flytube.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "flytube.image" . | quote}}
          imagePullPolicy: {{ include "flytube.imagePullPolicy" . | quote }}
          env:
            - name: USER
              value: "{{ required "user value is required" .Values.env.user }}"
            - name: REMOTE_HOST
              value: "{{ required "remoteHost value is required" .Values.env.remoteHost }}"
            - name: SOURCE_PORT
              value: "{{required "sourcePort value is required" .Values.env.sourcePort }}"
            - name: TARGET_HOST
              value: "{{required "targetHost value is required" .Values.env.targetHost }}"
            - name: TARGET_PORT
              value: "{{required "targetPort value is required" .Values.env.targetPort }}"
            - name: CERTIFICATE_PATH
              value: "/certs"
            - name: REMOTE_PORT
              value: {{ default .Values.env.remotePort  "22" | quote}}
            - name: SLEEP_DURATION
              value: {{ default .Values.env.sleepDuration  "5" | quote}}
          volumeMounts:
            - name: certificates
              mountPath: "/certs"
              readOnly: true
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
      volumes:
        - name: certificates
          secret:
            secretName: {{ include "flytube.secretname" . }}
            defaultMode: 0600
