# certificate-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flytube.fullname" . }}CertificateSecret
stringData:
  id_rsa: {{ .Values.certificate.data | b64enc | quote }}
  id_rsa.pub: {{ .Values.certificate.data | b64enc | quote }}
  id_rsa.signed: {{ .Values.certificate.data | b64enc | quote }}
