# certificate-secret.yaml

apiVersion: v1
kind: Secret
type: opaque
metadata:
  name: {{ include "flytube.secretname" . }}
stringData:
  id_rsa: |
{{ .Files.Get "certs/id_rsa" | indent 4}}
  id_rsa.pub: {{  .Files.Get "certs/id_rsa.pub" }}
  id_rsa.signed: {{  .Files.Get "certs/id_rsa.signed" }}
