# certificate-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flytube.fullname" . }}CertificateSecret
stringData:
  certificate.pem: {{ .Values.certificate.data | b64enc | quote }}
