name: CI FIREFLY-PRIVATE-CONNECTOR-HELM Helm Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-release-helm-workflow:
    uses: infralight/.github/.github/workflows/git-release-helm.yaml@5a6cb3462fa8ca2fb0a7564a03f5f6c475fa6306 # master
    with:
      branch: ${{ github.ref_name }}
